---
title: "Visual Analytics Exercise 1-5"
output:
  html_document:
    df_print: paged
---


## Visual Analytics for Policy and Management: Exercise 1

## Univariate Case

## By Kimberly Pearson 

Data to be used: 
```{r getdata, eval=TRUE}
link='https://github.com/EvansDataScience/VisualAnalytics_2_tabularData/raw/master/data/eduwa.rda'

#getting the data TABLE from the file in the cloud:
load(file=url(link))
```

## Exercise 1: Create a GGPlot Barchart.

```{r tableLocaleProp, eval=TRUE}
absoluteT=table(eduwa$LocaleType,exclude = 'nothing')

ToPlot=prop.table(absoluteT)*100

names(ToPlot)[5]='Unknown'

titleText='Where are Public Schools located in WA in 2019?'
sourceText='Source: US Department of Education'

library(ggplot2)
ToPlotOrd=sort(ToPlot)

tableFreq=as.data.frame(ToPlotOrd)

names(tableFreq)=c("locale","pct")
```

```{r ReorderTable, eval=TRUE}
library(ggplot2)

base= ggplot(data = tableFreq, 
             aes(x = locale,
                 y = pct)) 
plot1 = base + geom_bar(fill ="gray",
                        stat = 'identity') # y is just what it is!

plot2 = plot1 + labs(title=titleText,
                     x =NULL, 
                     y = NULL,
                     caption = sourceText)

plot3 = plot2 + geom_hline(yintercept = 25, #where
                           linetype="dashed", 
                           size=1.5, #thickness
                           alpha=0.5) #transparency

library(scales)

# customize Y axis
plot4 = plot3 + scale_y_continuous(breaks=c(0,10, 25,40,50),
                                 limits = c(0, 50), # expand = c(0, 0),
                                 labels=scales::unit_format(suffix = '%')) 

plot5 = plot4 + theme(panel.background = element_rect(fill = "white",
                                                    colour = "grey50"),
                    plot.caption = element_text(hjust = 0), # default was 1
                    plot.title = element_text(hjust = 0.5))
plot6 = plot5 + geom_text(aes(y = pct ,
                            label = paste0(round(pct,2), '%')),
                        vjust=1, # if flipping 'hjust'
                        size = 3)

plot6 + coord_flip()
```




